// <auto-generated />
using System;
using FashionHub.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FashionHub.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FashionHub.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Shirt"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Bags"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Trouser"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Shoes"
                        });
                });

            modelBuilder.Entity("FashionHub.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Tech City",
                            Name = "Jiji",
                            PhoneNumber = "6669990000",
                            PostalCode = "12121",
                            State = "IL",
                            StreetAddress = "123 Tech St"
                        },
                        new
                        {
                            Id = 2,
                            City = "Vid City",
                            Name = "Jumia",
                            PhoneNumber = "7779990000",
                            PostalCode = "66666",
                            State = "IL",
                            StreetAddress = "999 Vid St"
                        },
                        new
                        {
                            Id = 3,
                            City = "Lala land",
                            Name = "AliExpress",
                            PhoneNumber = "1113335555",
                            PostalCode = "99999",
                            State = "NY",
                            StreetAddress = "999 Main St"
                        });
                });

            modelBuilder.Entity("FashionHub.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("OrderHeaderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderHeaderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("FashionHub.Models.OrderHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Carrier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OrderTotal")
                        .HasColumnType("float");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PaymentDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShippingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("OrderHeaders");
                });

            modelBuilder.Entity("FashionHub.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            Color = "Blue",
                            Description = "This remarkable high waist Jean is beautiful, trendy and affordable for Fashionable women. It is designed and tailored to slim fit and trim all waist. It is Stretchy and elastic. It does not fade. it is durable and long lasting. It gives you a perfect shape you desire. It is so rugged and does not wear out. It is comfortable and superb. Every woman deserve to be beautiful. Admire other people's beauty without questioning your own. ",
                            ListPrice = 99.0,
                            Name = "Ladies High Waist Skinny Jean- Blue",
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Size = "27-34"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Color = "Blue, Green, Black",
                            Description = "Men's 2 In 1 Short Sleeve Round Neck T-Shirt & Shorts Set - BlueQuality is our number one priority. This is a very stylish men's T-shirt suit that include a short sleeve and a pair of shorts. It has been carefully designed to stand the test of time. Make sure you can wear it for a long time. You can wear them in interesting places at any time of the day, such as walking, dating and going to work. I believe that I really have many advantages, such as materials, ventilation, style, you need to wear them to feel.   It has a range of details that will make you stand out. No matter how long you wear it, it will continue to maintain its solid form.",
                            ListPrice = 99.0,
                            Name = "Men's 2 In 1 Short Sleeve Round Neck T-Shirt & Shorts Set - Blue",
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Size = "M, L, XL, XXL"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Color = "Black, Green, Black, Peach, Brown e.t.c",
                            Description = "Available in a variety of colors, it is easy to match with a variety of clothes. A popular rectangular underarm bag for parties, leisure, commuting, travel and more.",
                            ListPrice = 99.0,
                            Name = "Riapawel Fashion Handbag Bag Shoulder Bags Square Bag",
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Size = "small"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Color = "Brown",
                            Description = "Made of high-quality PU, this elegant set includes a card bag, a wallet, a clutch bag, a shoulder bag and a coin purse. The printed design makes you outstanding from others. The wallet is without letter print. Perfect for office ladies who are in business, working, shopping, or dating.",
                            ListPrice = 99.0,
                            Name = "New Ladies Women Handbag - Brown",
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Size = "small"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            Color = "Black",
                            Description = "Our shop specializes in quality men's and women's clothing. Believe me, you own one of our products, enough to show off like your friends. To avoid choosing the wrong size, please read the size label carefully. Please select the size according to the \"foot length\".If the feet are thick and wide, please buy large shoes; if the shoes are too large, we recommend wearing insoles.",
                            ListPrice = 99.0,
                            Name = "Ladies Sexy Cross Strap High Heels Black",
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Size = "38-42"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Color = "Black & Grey",
                            Description = "Joggers from Bubbling Fashion Store comes with its own uniqueness, its brings out the style in you whenever it is worn, joggers are versatile choice for casual clothing which brings out the brilliant gear for chilled days, it is for every one who is stylish and urban. The fabrics are made from high quality which are manufactured and carefully paid to durability and comfortability Men designed combat joggers with high quality material from outfit and sportswear.",
                            ListPrice = 99.0,
                            Name = "Well-tailored Unisex Up & Down Joggers - Black & Grey",
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Size = "S, M, L, XL, XXL, XXXL"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Color = "Multi",
                            Description = "Easy to wash and quickly dry when you wash. it made of cotton blended material. nice for both casual and cooperate. Our sweatpants and joggers are made for extreme Comfort, fitted with pristine precision and finely crafted with the highest quality fabric. With these , you do not only feel the difference in fitting and comfort but also have access to a wide range of style purposes. These joggers can be worn for different days in a plethora of ways. Flip Wears now has a history of creating functional yet stylish street-wear, covering everything from retro styles to forward-thinking pieces.",
                            ListPrice = 99.0,
                            Name = "Crew Clothing Cargo Joggers",
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Size = "S, M, L, XL, XXL, XXXL, XXXXL"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Color = "Black",
                            Description = "100% Cotton material gives you comfortable feeling with High Quality, Cool, Charming & Fashionable Nail the smart and demure look with this, Featuring high round neck, short shirt sleeves , Cotton fabric ,",
                            ListPrice = 99.0,
                            Name = "Ladies Round Neck Polo Printed T-Shirt",
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Size = "M, L, XL, S"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Color = "Yellow",
                            Description = "100% Cotton material gives you comfortable feeling with High Quality, Cool, Charming & Fashionable Nail the smart and demure look with this, Featuring high round neck, short shirt sleeves , Cotton fabric ,",
                            ListPrice = 99.0,
                            Name = "Boss Lady Ladies Round Neck Polo Printed T-Shirt",
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Size = "M, L, XL, S"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Color = "White",
                            Description = "The fabric is cool and relaxed fit create an extremely flattering silhouette and produces a versatile piece that would go with any style of pant for an effortless, laid-back cool look. And at a brilliant value, these top will ensure that you stand out from the crowd this season without breaking the bank! ",
                            ListPrice = 99.0,
                            Name = "Top Long Sleeve Top For Ladies - Knitting Top",
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Size = "S, M, L"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Color = "Grey",
                            Description = "Lightweight design is easy for carrying: Made From Durable Polyester Fabric with good features of comfortable and portable.",
                            ListPrice = 99.0,
                            Name = "EILIFINTE B06 Casual Crossbody Shoulder Chest Bag-Grey",
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Size = "small"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Color = "Gold",
                            Description = "This fashionable handbag is made of durable, high height leather, leather, decorated with leather, water, cocoa, and cocoa for a long time",
                            ListPrice = 99.0,
                            Name = "Shiny Rhinestone Evening Banquet Bag Handbag Purse - Gold",
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Size = "small"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Color = "multi",
                            Description = "Lightweight design is easy for carrying: Made From Durable Polyester Fabric with good features of comfortable and portable.",
                            ListPrice = 99.0,
                            Name = "EILIFINTE B01 Ladies Causal Stylish Shoulder Bag - Plaid",
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Size = "small"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            Color = "beige",
                            Description = "Material: PU leatherColor: beigeSize: 37, 38, 39, 40Gender: women",
                            ListPrice = 99.0,
                            Name = "Ladies Square Heels Sandals Elegant Summer Slippers",
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Size = "37-40"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            Color = "Black",
                            Description = "Another beautiful fashion sandals with unique mid heels. One of lasted sandals on Vogue from well know brand fang Kenneth. Is very beautiful, lovely, strong and the heels is very balance that any lady that love unique design can wear it. Is one beautiful sandals you can wear for long. Thank you for always trusting me for the best.",
                            ListPrice = 99.0,
                            Name = "Fang Kenneth New Design Ladies Fashion Sandals-Black",
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Size = "38-41"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            Color = "Multiple",
                            Description = "Beautiful multiple colors sandals, lovely sandals that can go with any colours of your choice. Nice sandals with perfect fitting. One of trendy Sandals ",
                            ListPrice = 99.0,
                            Name = "Elegant Ladies Multiple Colour Sandals",
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Size = "37-41"
                        });
                });

            modelBuilder.Entity("FashionHub.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "\\images\\products\\product-1\\3f8cfae8-6e8b-4f77-a981-e2af59d2bec6.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "\\images\\products\\product-2\\f67ce5a4-6e43-460b-a448-94843acc6717.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "\\images\\products\\product-3\\af12e749-60c4-4998-a03b-cf84562b6a28.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "\\images\\products\\product-4\\5dc8829e-951c-4723-98a9-9a477a271094.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "\\images\\products\\product-5\\906d4ff7-589d-43ec-883a-49f486a19351.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "\\images\\products\\product-6\\71758c64-0d21-4f1b-b379-316f07753f33.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "\\images\\products\\product-7\\7dad1cdd-0c8c-4b34-b257-5827e2b386cd.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "\\images\\products\\product-8\\84c8770c-0262-4ea4-9609-e100bf001a3e.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "\\images\\products\\product-9\\30f6e2a5-e9c0-4f76-b519-42b39dadf6a0.jpg",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "\\images\\products\\product-10\\4e22b28c-0fea-44d6-89a1-e5fb478e5646.jpg",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "\\images\\products\\product-11\\202f3d19-9e90-48fc-8ae5-160a355bbc7c.jpg",
                            ProductId = 11
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "\\images\\products\\product-12\\6d98b3eb-715f-40a5-b7a4-3295091d531e.jpg",
                            ProductId = 12
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "\\images\\products\\product-13\\f0deca55-6e82-4988-9955-ce5940928bec.jpg",
                            ProductId = 13
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "\\images\\products\\product-14\\0a5b0367-dda0-4b5f-b158-935a1c3c5f4b.jpg",
                            ProductId = 14
                        },
                        new
                        {
                            Id = 15,
                            ImageUrl = "\\images\\products\\product-15\\92aeb63e-9661-4c5f-8ee9-9dcc22486684.jpg",
                            ProductId = 15
                        },
                        new
                        {
                            Id = 16,
                            ImageUrl = "\\images\\products\\product-16\\9afd6a4f-c248-473f-b3bc-4ff9237276d1.jpg",
                            ProductId = 16
                        });
                });

            modelBuilder.Entity("FashionHub.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FashionHub.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("CompanyId");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("FashionHub.Models.OrderDetail", b =>
                {
                    b.HasOne("FashionHub.Models.OrderHeader", "OrderHeader")
                        .WithMany()
                        .HasForeignKey("OrderHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionHub.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderHeader");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FashionHub.Models.OrderHeader", b =>
                {
                    b.HasOne("FashionHub.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("FashionHub.Models.Product", b =>
                {
                    b.HasOne("FashionHub.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FashionHub.Models.ProductImage", b =>
                {
                    b.HasOne("FashionHub.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FashionHub.Models.ShoppingCart", b =>
                {
                    b.HasOne("FashionHub.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionHub.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FashionHub.Models.ApplicationUser", b =>
                {
                    b.HasOne("FashionHub.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("FashionHub.Models.Product", b =>
                {
                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
